### ISSUE TITLE
Page scan source should be listed in content.opf

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/victor-hugo_notre-dame-de-paris_isabel-f-hapgood#3]
Need to add another `<dc:source>` tag pointing at the Google Books source of the page scans.

**Comment by vr8hub** [comment]
Good grief. I know that, you caught that on one of my other books. I don't know how I missed that. My apologies, fixed.

**Comment by drgrigg** [comment]
It’s something i often miss myself until i go through a review checklist.
