### ISSUE TITLE
Awkward phrase in long description

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/victor-hugo_notre-dame-de-paris_isabel-f-hapgood#6]
This is just a personal writing-style thing, but you have:

> Hugo’s tragic novel is an ode to gothic architecture in general and Notre-Dame de Paris’ in particular

The trailing apostrophe is awkward. I think this would be better as:

> Hugo’s tragic novel is an ode to gothic architecture in general and that of Notre-Dame de Paris in particular

**Comment by vr8hub** [comment]
No worries, I'm not married to that apostrophe. :) Changed.
